Navbar mobile
karenmscg/Portif-lio pull request #4
Opened 2021-08-03 21:56 UTC by karenmscg

Navbar responsive
Pages

2021-08-04 17:26 UTC, natandias requested changes
É preciso remover os espaços das rotas para evitar problemas. Outra coisa, evite puxar a _branch_ para uma funcionalidade nova de uma outra _branch_ que pertence a uma PR aberta. Como esse projeto aqui é de uma pessoa só, não tem problema, mas quando trabalhar em um projeto com mais de desenvolvedores isso não pode acontecer, porque fica praticamente impossível saber quais alterações são dessa PR nova mesmo, e aí caso altere alguma coisa aqui, vai dar conflito na outra PR que tá aberta e vai rolar bastante problema pra juntar as duas depois.

2021-08-04 17:26 UTC, natandias commented on src/components/Menu/index.js
> +        <NavLinks onclick={closeMenu} to="/ about">
Esses _onclIck_ nos Links são necessários? Testei sem e funcionou. Outra coisa, é necessário remover esses espaços da rota pra não ter problemas depois, se notar bem, quando você coloca esse espaço entre a barra e a primeira letra, a url sofre _encoding_ ficando assim: `http://localhost:3000/%20about`, enquanto o certo seria que ela ficasse assim: `http://localhost:3000/about`. Você vai precisar alterar aqui e lá na declaração das rotas no App.js.

2021-08-04 17:26 UTC, natandias commented on src/components/Pages/About.js
> +import React from 'react'
Tenta manter o padrão da adição dos `;` também, alguns tem `;` e outros não, tanto faz usar ele ou não, o funcionamento é o mesmo, mas se optar por usar, use em todos os arquivos.

2021-08-04 17:26 UTC, natandias commented on src/components/Pages/About.js
> +import React from 'react'
Se possível configure o Prettier que ai quando salvar o arquivo, ele já formata da maneira que você definir.

2021-08-04 17:26 UTC, natandias commented on src/components/Menu/index.js
> +  const menuToggle = () => {
Se preferir pode fazer essa função em uma linha só: 
```suggestion
const menuToggle = () => setOpen(!open);
```

2021-08-04 17:26 UTC, natandias commented on src/components/Menu/index.js
> +        <img src={logo} />
Faltou um _alt_ na imagem.

2021-08-04 17:26 UTC, natandias commented on src/components/Menu/index.js
> +  const [open, setOpen] = useState(false);
Se puder deixar a variável mais explícita é uma boa, ao invés de apenas _open_ você pode usar algo mais descritivo, como _isMenuOpen_. Explícito é sempre melhor que implícito.

2021-08-04 17:26 UTC, natandias commented on src/components/Menu/index.js
> +        <NavLinks onclick={closeMenu} to="/ works">
Aqui também, a rota possui um espaço no meio.

2021-08-04 17:26 UTC, natandias commented on src/components/Pages/About.js
> +        <div>
Caso for retornar apenas um componente, não é necessário colocá-lo dentro de uma _div_, caso for retornar mais de um e a _div_ seja apenas um _wrapper_, é melhor usar o fragment do React: [React Fragments](https://pt-br.reactjs.org/docs/fragments.html), é o ideal pra não precisar usar uma _div_ que possui um valor semântico.

2021-08-04 17:26 UTC, natandias commented on src/components/Menu/index.js
> +import React from "react";
Ao invés do _import_ separado do useState, você importar numa linha só:
```suggestion
import React, { useState } from "react";
```

2021-08-04 17:26 UTC, natandias commented on src/components/HeroSection/HeroSection.js
> +  font-size: 48px;
Evite usar pixels para elementos como _font-size_ e _margin_, fica mais difícil para fazer layouts responsivos, prefira usam [EM ou REM](https://tableless.com.br/unidade-pixels-em-rem/). Pode usar pixels também, caso seja necessário, mas dê preferência para os outros tipos de unidades.

2021-08-04 17:26 UTC, natandias commented on src/components/Footer/index.js
> +      <A
É bom evitar também usar componentes com nome semelhante aos elementos do html pra evitar confusões. Acho que pode usar nesse caso algo como, por exemplo, _styledLinks_.

2021-08-04 17:26 UTC, natandias commented on src/App.js
> +            <Route path="/ about" exact component={About} />
Remover espaços das rotas.

2021-08-04 17:26 UTC, natandias commented on src/App.js
> +          <Button onClick={() => themeToggler()}> My Dark Mode </Button>
Se não me engano, pode usar só:
```suggestion
onClick={themeToggler}
```
Acho que funciona.

2021-08-04 17:26 UTC, natandias commented on src/components/HeroSection/HeroSection.js
> +export const ButtonContainer = styled.div`
Evitar deixar elementos vazios no código.

2021-08-04 17:26 UTC, natandias commented on src/components/HeroSection/index.js
> +        <Img src={imageWork} />
Lembra de adicionar um _alt_ em todas as imagens.

2021-08-05 21:10 UTC, karenmscg commented
eu espero q tenha dado certo

2021-08-05 21:10 UTC, merged